# fly.toml app configuration file generated for crossfit-front-v1 on 2024-11-22T00:59:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crossfit-front-v1'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
